version: '3.4'

volumes:
  pgdata-auth:
    external: false

services:
  authorization-play.postgres:
    container_name: authorization-play.postgres
    restart: always
    image: ${DOCKER_REGISTRY-}postgres:latest
    volumes:
      - pgdata-auth:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth

  authorization-play.api:
    image: ${DOCKER_REGISTRY-}authorizationplayapi
    build:
      context: .
      dockerfile: authorization-play.Api/Dockerfile

  authorization-play.testapi:
    image: ${DOCKER_REGISTRY-}authorizationplaytestapi
    build:
      context: .
      dockerfile: authorization-play.TestApi/Dockerfile

